
services:
  mariadb:
    container_name: mariadb
    build:
     context: ./requirements/mariadb/
    volumes:
      - db:/var/lib/mysql/
    networks:
      - default
    environment:
    	- MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=somewordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    init: true
    restart: on-failure
    
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    volumes:
      - app:/var/www/wordpress/
    networks:
      - default
    environment:
    	- WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      
    init: true
    restart: on-failure
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    volumes:
      - app:/var/www/wordpress/
    networks:
      - default
    ports:
      - '443:443'
    init: true
    restart: on-failure
    depends_on:
      - wordpress
      
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rsilva-e/data/mariadb
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rsilva-e/data/wordpress/
networks:
  default:
    driver: bridge
