services:
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    secrets:
      - secrets_inception
    volumes:
      - app:/var/www/html/wordpress/
    networks:
      - default
    env_file: .env
    init: true
    restart: on-failure
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
     context: ./requirements/mariadb/
    secrets:
      - secrets_inception
    volumes:
      - db:/var/lib/mysql/
    networks:
      - default
    env_file: .env
    init: true
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
    volumes:
      - app:/var/www/html/wordpress/
    networks:
      - default
    ports:
      - '443:443'
    init: true
    restart: on-failure
    depends_on:
      - wordpress
secrets:
  secrets_inception:
    file: ../secrets/secrets.txt
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rsilva-e/data/db/
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rsilva-e/data/wp/
networks:
  default:
    driver: bridge
